### ISSUE TITLE
API Documentation discovery

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/gravitee-management-rest-api#42]
Do you think it will be interesting to automatically discover some API documentations when a user add an API ? For example, by default the swagger documentation can be found at [endpoint]/swagger.json...

**Comment by brasseld** [comment]
I'm not sure that "auto-discovery" documentation is a good choice. 
First, this is only working with Swagger because we know that the documentation is available at [endpoint]/swagger.json.
Then, for production environment, I think that providing documentation from the same server is not a good option. I would prefer to isolate the documentation from the "runtime".

IMHO, when creating API through the webui, it would be a good way to provide some kind of "creation flow" to let the API publisher to :
* 1) Create an API by providing global configuration (name, version, context path, endpoint)
* 2) Associate documentation to the newly created API
* 3) Associate members ?

**Comment by brasseld** [comment]
This issue was moved to gravitee-io/ichiou#11
